#!/usr/bin/env python3
#generate_verilog.py
"""
generate_verilog_from_pd_eco.py

Generate a gate-level Verilog netlist from:
  - data_structures.json     (generated by generate_db.py)
  - build/<design>/<design>_mapped_netlist_graph_after_pd_eco.json

Rules:
  - Spares are instances whose entry in the AFTER-PD graph has an empty
    sink list (inst -> []).
  - Find a sky130_fd_sc_hd__conb_1 instance and use its LO pin's net
    (bit ID) as the global tie-low.
  - For each spare instance, tie all NON-OUTPUT pins to that LO bit.
  - Output pins (X, Y, Z, Q, LO, HI, etc.) are left as-is.
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List, Set

# -----------------------------
# I/O helpers
# -----------------------------


def load_json(path: Path):
    with open(path, "r") as f:
        return json.load(f)


def write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


# -----------------------------
# Extract instances from data_structures.json
# -----------------------------


def extract_instances_from_data_structures(ds_raw) -> Dict[str, dict]:
    """
    data_structures.json format (from generate_db.py):

      {
        "logical_db": { inst_name: { "type": ..., "pins": ... }, ... },
        "netlist_graph": { ... },
        "fabric_db": ...,
        ...
      }

    We just return logical_db (already the instances dict).
    """
    if not isinstance(ds_raw, dict):
        raise ValueError("data_structures.json top-level is not a dict")

    logical_db = ds_raw.get("logical_db")
    if not isinstance(logical_db, dict):
        raise ValueError("data_structures.json missing 'logical_db' dict")

    return logical_db


COMMON_OUTPUT_NAMES = {
    "X", "Y", "Z", "ZN",
    "Q", "QN", "Q_N",
    "LO", "HI",
}


def is_output_pin(pin_name: str) -> bool:
    return pin_name in COMMON_OUTPUT_NAMES


def find_tie_low_conb(instances: Dict[str, dict]):
    """
    Search for a sky130_fd_sc_hd__conb_1 instance with a LO pin.
    Return (inst_name, lo_bit) where lo_bit is the integer/ID of LO.
    """
    for inst_name, inst in instances.items():
        ctype = inst.get("type", "")
        if ctype != "sky130_fd_sc_hd__conb_1":
            continue
        pins = inst.get("pins", {})
        lo_bits = pins.get("LO")
        if lo_bits and len(lo_bits) >= 1:
            return inst_name, lo_bits[0]

    raise RuntimeError(
        "Could not find sky130_fd_sc_hd__conb_1 with LO pin in logical_db."
    )


# -----------------------------
# Graph / spare detection
# -----------------------------


def find_spares_from_after_graph(
    instances: Dict[str, dict],
    graph_after: Dict[str, List[str]],
    tie_low_inst: str,
) -> Set[str]:
    """
    Spares are instances whose entry in the after-PD graph has an empty
    sink list:  inst -> [].

    We:
      - Look at graph_after keys (drivers).
      - If sinks list is empty and inst is in instances,
        and inst != tie_low_inst, we mark it as a spare.
    """
    spares: Set[str] = set()

    for drv, sinks in graph_after.items():
        if drv == tie_low_inst:
            continue
        if drv in instances and (not sinks):
            spares.add(drv)

    return spares


# -----------------------------
# Net collection & naming
# -----------------------------


def collect_all_net_bits(instances: Dict[str, dict]) -> Set[int]:
    """
    Gather all bit IDs used in the 'pins' of all instances.
    Assumes bits are integers (like 2474, 1041, ...).
    """
    net_bits: Set[int] = set()
    for inst in instances.values():
        pins = inst.get("pins", {})
        for bits in pins.values():
            for b in bits:
                if isinstance(b, int):
                    net_bits.add(b)
                else:
                    try:
                        net_bits.add(int(b))
                    except Exception:
                        pass
    return net_bits


def net_name(bit) -> str:
    """Map a net bit ID to a Verilog wire name."""
    return f"n{bit}"


# -----------------------------
# Verilog generation helpers
# -----------------------------


def escape_inst_name(name: str) -> str:
    """
    Turn a Yosys-style instance name into a legal Verilog identifier
    using an escaped identifier: \name_with_weird_chars<space>
    """
    return "\\" + name + " "


def pins_with_pd_overrides(
    inst_name: str,
    inst: dict,
    is_spare: bool,
    tie_low_bit,
) -> Dict[str, List[int]]:
    """
    Build the effective pins for an instance, applying power-down ECO:
      - if not a spare, keep original pins as-is.
      - if a spare, tie all NON-OUTPUT pins to tie_low_bit.
    """
    pins = inst.get("pins", {})
    effective_pins: Dict[str, List[int]] = {}

    for pin_name, bits in pins.items():
        # Normalize bits to int list
        norm_bits: List[int] = []
        for b in bits:
            if isinstance(b, int):
                norm_bits.append(b)
            else:
                try:
                    norm_bits.append(int(b))
                except Exception:
                    continue

        if not is_spare:
            effective_pins[pin_name] = norm_bits
            continue

        # Spare logic:
        if is_output_pin(pin_name):
            # Do NOT tie outputs to LO; keep original nets
            effective_pins[pin_name] = norm_bits
        else:
            # Inputs (and everything non-output) get tied to LO
            if norm_bits:
                effective_pins[pin_name] = [tie_low_bit] * len(norm_bits)
            else:
                effective_pins[pin_name] = [tie_low_bit]

    return effective_pins


def generate_verilog(
    design: str,
    instances: Dict[str, dict],
    graph_after: Dict[str, List[str]],
) -> str:
    """
    Build the full Verilog source as a string.
    Module name: <design>_pd_eco

    Uses graph_after to determine spares (empty fanout inst -> []),
    and applies tie-low overrides via conb_1 LO.
    """
    # 1) tie-low provider
    tie_low_inst, tie_low_bit = find_tie_low_conb(instances)

    # 2) find spares from AFTER-PD graph
    spares = find_spares_from_after_graph(instances, graph_after, tie_low_inst)

    # 3) collect nets
    net_bits = collect_all_net_bits(instances)
    net_bits.add(int(tie_low_bit))  # ensure LO net is declared

    # 4) start building Verilog text
    lines: List[str] = []

    lines.append("// Auto-generated PD-ECO gate-level netlist")
    lines.append(f"// Design: {design}")
    lines.append("// Sources:")
    lines.append("//   data_structures.json (logical_db)")
    lines.append("//   <design>_mapped_netlist_graph_after_pd_eco.json")
    lines.append("")
    lines.append(f"module {design}_pd_eco;")
    lines.append("")

    # 5) wire declarations
    if net_bits:
        lines.append("  // Internal nets")
        for b in sorted(net_bits):
            lines.append(f"  wire {net_name(b)};")
        lines.append("")

    # 6) instance instantiations
    lines.append("  // Cell instances")
    for inst_name, inst in instances.items():
        ctype = inst.get("type", "UNKNOWN")
        is_spare = inst_name in spares

        eff_pins = pins_with_pd_overrides(
            inst_name=inst_name,
            inst=inst,
            is_spare=is_spare,
            tie_low_bit=tie_low_bit,
        )

        escaped_name = escape_inst_name(inst_name)

        # Build the .PIN(net) list
        conn_strs = []
        for pin_name, bits in eff_pins.items():
            if not bits:
                conn_strs.append(f".{pin_name}()")
                continue

            if len(bits) == 1:
                conn_strs.append(f".{pin_name}({net_name(bits[0])})")
            else:
                net_list = ", ".join(net_name(b) for b in bits)
                conn_strs.append(f".{pin_name}({{{ {net_list} }}})")

        conn_body = ", ".join(conn_strs)
        lines.append(f"  {ctype} {escaped_name} ( {conn_body} );")

    lines.append("")
    lines.append("endmodule")
    lines.append("")

    return "\n".join(lines)


# -----------------------------
# Main
# -----------------------------


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate a PD-ECO gate-level Verilog netlist "
            "from data_structures.json and mapped_netlist_graph_after_pd_eco."
        )
    )
    parser.add_argument(
        "--design",
        required=True,
        help="Design name (expects build/<design>/...)",
    )

    args = parser.parse_args()
    design = args.design

    base_dir = Path("build") / design
    graph_after_path = base_dir / f"{design}_mapped_netlist_graph_after_pd_eco.json"
    out_verilog_path = base_dir / f"{design}_pd_eco_netlist.v"
    ds_path = base_dir / f"data_structures.json"

    if not ds_path.exists():
        raise FileNotFoundError(f"data_structures.json not found: {ds_path}")
    if not graph_after_path.exists():
        raise FileNotFoundError(f"After-PD graph not found: {graph_after_path}")

    print(f"[VERILOG] Design: {design}")
    print(f"[VERILOG] data_structures: {ds_path}")
    print(f"[VERILOG] after-PD graph: {graph_after_path}")
    print(f"[VERILOG] output Verilog: {out_verilog_path}")

    ds_raw = load_json(ds_path)
    instances = extract_instances_from_data_structures(ds_raw)
    graph_after = load_json(graph_after_path)

    print(f"[VERILOG] Instances in logical_db: {len(instances)}")
    print(f"[VERILOG] Drivers in after-PD graph: {len(graph_after)}")

    verilog_src = generate_verilog(design, instances, graph_after)
    write_text(out_verilog_path, verilog_src)

    print("[VERILOG] Done. Wrote gate-level netlist.")


if __name__ == "__main__":
    main()

# how to run: python src/generate_verilog.py --design <design>