# route.tcl
# Generic routing script for OpenROAD
# Usage: openroad -exit route.tcl

# --- 1. Setup Environment Variables ---
# We get the design name from the environment (e.g., "6502")
if { [info exists ::env(DESIGN_NAME)] } {
    set design_name $::env(DESIGN_NAME)
} else {
    puts "Error: DESIGN_NAME environment variable not set."
    exit 1
}

# Define directory paths
set build_dir "build/${design_name}"
set platform_dir "tech" 

puts "--- Starting Routing for Design: $design_name ---"

# --- 2. Load Platform Files ---
# Read the physical library (LEF)
read_lef "${platform_dir}/sky130_fd_sc_hd.lef"

# Read the timing library (Lib)
read_liberty "${platform_dir}/sky130_fd_sc_hd__tt_025C_1v80.lib"

# --- 3. Load Design Files ---
# Read the placement (DEF) generated by make_def.py
read_def "${build_dir}/${design_name}/${design_name}_fixed.def"

# Read the renamed netlist (Verilog) generated by rename.py
read_verilog "${build_dir}/${design_name}/${design_name}_renamed.v"

# --- 4. Routing Steps ---
# Global Route: Plans the approximate paths for wires
# We save the congestion report for Phase 4 visualization
global_route -congestion_report_file "${build_dir}/${design_name}/${design_name}_congestion.rpt"

# Detailed Route: Actually draws the metal wires [cite: 169]
detailed_route -output_drc "${build_dir}/${design_name}/${design_name}_drc.rpt"

# --- 5. Extraction & Analysis ---
# Extract Parasitics: Calculates resistance/capacitance of wires
extract_parasitics

# Write the SPEF file (Critical for Phase 5 STA)
write_spef "${build_dir}/${design_name}/${design_name}.spef"

# Report Congestion [cite: 169]
report_congestion -metrics "${build_dir}/${design_name}/${design_name}_congestion_metrics.txt"

# --- 6. Save Final Result ---
# Write the final routed DEF for visualization
write_def "${build_dir}/${design_name}/${design_name}_routed.def"

puts "--- Routing Complete. Files saved to ${build_dir}/${design_name} ---"
